const productos = [
  {
    id: 01,
    tipo: "Buzon",
    nombre: "Buzon Gamer",
    precio: 1400,
    foto: "./media/Buzones-Japon-01.jpg",
  },
  {
    id: 02,
    tipo: "Buzon",
    nombre: "Buzon Buena Onda",
    precio: 1400,
    foto: "./media/Buzones-Japon-02.jpg",
  },
  {
    id: 03,
    tipo: "Buzon",
    nombre: "Buzon Muñeca Poseida",
    precio: 1000,
    foto: "./media/Buzones-Japon-03.jpg",
  },
  {
    id: 04,
    tipo: "Buzon",
    nombre: "Buzon Pinguino Falopa",
    precio: 1000,
    foto: "./media/Buzones-Japon-04.jpg",
  },
  {
    id: 05,
    tipo: "Buzon",
    nombre: "Buzon Japo-Chino",
    precio: 1400,
    foto: "./media/Buzones-Japon-05.jpg",
  },
  {
    id: 06,
    tipo: "Buzon",
    nombre: "Buzon Noir",
    precio: 1500,
    foto: "./media/Buzones-Japon-06.jpg",
  },
  {
    id: 07,
    tipo: "Buzon",
    nombre: "Buzon Hombre de Nieve",
    precio: 4500,
    foto: "./media/Buzones-Japon-07.jpg",
  },
  {
    id: 08,
    tipo: "Buzon",
    nombre: "Buzon Ejecutivo",
    precio: 3800,
    foto: "./media/Buzones-Japon-08.jpg",
  },
  {
    id: 09,
    tipo: "Buzon",
    nombre: "Buzon Quemierdaeseso",
    precio: 3800,
    foto: "./media/Buzones-Japon-09.jpg",
  },
  {
    id: 10,
    tipo: "Buzon",
    nombre: "Buzon Montaña Hentai",
    precio: 3800,
    foto: "./media/Buzones-Japon-10.jpg",
  },
  {
    id: 11,
    tipo: "Buzon",
    nombre: "Buzon Minero",
    precio: 2900,
    foto: "./media/Buzones-Japon-11.jpg",
  },
  {
    id: 12,
    tipo: "Buzon",
    nombre: "Buzon Pio Pio",
    precio: 1200,
    foto: "./media/Buzones-Japon-12.jpg",
  },
  {
    id: 13,
    tipo: "Buzon",
    nombre: "Buzon Apple Nipon",
    precio: 1000,
    foto: "./media/Buzones-Japon-13.jpg",
  },
  {
    id: 14,
    tipo: "Buzon",
    nombre: "Buzon Kung Fu Panda",
    precio: 1300,
    foto: "./media/Buzones-Japon-14.jpg",
  },
  {
    id: 15,
    tipo: "Buzon",
    nombre: "Buzon Monasterio",
    precio: 2300,
    foto: "./media/Buzones-Japon-15.jpg",
  },
  {
    id: 16,
    tipo: "Buzon",
    nombre: "Buzon Japo-Australiano",
    precio: 2400,
    foto: "./media/Buzones-Japon-16.jpg",
  },
  {
    id: 17,
    tipo: "Buzon",
    nombre: "Bzon Matroska Nipon",
    precio: 800,
    foto: "./media/Buzones-Japon-17.jpg",
  },
  {
    id: 18,
    tipo: "Buzon",
    nombre: "Buzon Bola de Fraile Enamorada",
    precio: 800,
    foto: "./media/Buzones-Japon-18.jpg",
  },
];
